version: '3'
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=qavi
      - MONGO_PASSWORD=mypassword
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=qavi
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
