version: '3'
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '2000:3000'
    environment:
      - NODE_ENV=production
    # env_file:
    # - ./.env
    command: node index.js
